spring.application.name=RpgBooking

spring.datasource.url=jdbc:mysql://localhost:3306/rpg_booking
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=46d3f996c96e31
spring.mail.password=490ad02476fd41

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

